// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/Operational/DigitalTwinLayerOperationalService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.Aas.GRPC.Lib.V3.Services.Operational {

  /// <summary>Holder for reflection information generated from Protos/Services/Operational/DigitalTwinLayerOperationalService.proto</summary>
  public static partial class DigitalTwinLayerOperationalServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/Operational/DigitalTwinLayerOperationalService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DigitalTwinLayerOperationalServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkRQcm90b3MvU2VydmljZXMvT3BlcmF0aW9uYWwvRGlnaXRhbFR3aW5MYXll",
            "ck9wZXJhdGlvbmFsU2VydmljZS5wcm90bxIfRlNSLkFhcy5HUlBDLkxpYi5W",
            "My5PcGVyYXRpb25hbBoZUHJvdG9zL0Fhc01vZGVscy5WMy5wcm90bxocUHJv",
            "dG9zL0Fhc0FwaU1vZGVscy5WMy5wcm90byKVAgoWT3BlcmF0aW9uSW52b2tl",
            "UmVxdWVzdBIRCglyZXF1ZXN0SWQYASABKAkSEgoKc3VibW9kZWxJZBgCIAEo",
            "CRIYChBvcGVyYXRpb25JZFNob3J0GAMgASgJEkEKDmlucHV0VmFyaWFibGVz",
            "GAQgAygLMikuRlNSLkFhcy5HUlBDLkxpYi5WMy5PcGVyYXRpb25WYXJpYWJs",
            "ZURUTxJBCg5pbm91dFZhcmlhYmxlcxgFIAMoCzIpLkZTUi5BYXMuR1JQQy5M",
            "aWIuVjMuT3BlcmF0aW9uVmFyaWFibGVEVE8SEQoJdGltZXN0YW1wGAYgASgD",
            "Eg8KB2lzQXN5bmMYByABKAgSEAoIaGFuZGxlSWQYCCABKAkiJQoQT3BlcmF0",
            "aW9uUmVxdWVzdBIRCglyZXF1ZXN0SWQYASABKAkiYQoPT3BlcmF0aW9uU3Rh",
            "dHVzEhEKCXJlcXVlc3RJZBgBIAEoCRI7Cg5leGVjdXRpb25TdGF0ZRgCIAEo",
            "DjIjLkZTUi5BYXMuR1JQQy5MaWIuVjMuRXhlY3V0aW9uU3RhdGUytQMKIkRp",
            "Z2l0YWxUd2luTGF5ZXJPcGVyYXRpb25hbFNlcnZpY2USjgEKHU9wZW5PcGVy",
            "YXRpb25JbnZvY2F0aW9uU3RyZWFtEjAuRlNSLkFhcy5HUlBDLkxpYi5WMy5P",
            "cGVyYXRpb25hbC5PcGVyYXRpb25TdGF0dXMaNy5GU1IuQWFzLkdSUEMuTGli",
            "LlYzLk9wZXJhdGlvbmFsLk9wZXJhdGlvbkludm9rZVJlcXVlc3QoATABEngK",
            "GU9wZW5PcGVyYXRpb25SZXN1bHRTdHJlYW0SJC5GU1IuQWFzLkdSUEMuTGli",
            "LlYzLk9wZXJhdGlvblJlc3VsdBoxLkZTUi5BYXMuR1JQQy5MaWIuVjMuT3Bl",
            "cmF0aW9uYWwuT3BlcmF0aW9uUmVxdWVzdCgBMAESgwEKGE9wZW5FeGVjdXRp",
            "b25TdGF0ZVN0cmVhbRIwLkZTUi5BYXMuR1JQQy5MaWIuVjMuT3BlcmF0aW9u",
            "YWwuT3BlcmF0aW9uU3RhdHVzGjEuRlNSLkFhcy5HUlBDLkxpYi5WMy5PcGVy",
            "YXRpb25hbC5PcGVyYXRpb25SZXF1ZXN0KAEwAUIrqgIoRlNSLkFhcy5HUlBD",
            "LkxpYi5WMy5TZXJ2aWNlcy5PcGVyYXRpb25hbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.Aas.GRPC.Lib.V3.AasModelsV3Reflection.Descriptor, global::FSR.Aas.GRPC.Lib.V3.Services.AasApiModelsV3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest.Parser, new[]{ "RequestId", "SubmodelId", "OperationIdShort", "InputVariables", "InoutVariables", "Timestamp", "IsAsync", "HandleId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest.Parser, new[]{ "RequestId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus.Parser, new[]{ "RequestId", "ExecutionState" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OperationInvokeRequest : pb::IMessage<OperationInvokeRequest> {
    private static readonly pb::MessageParser<OperationInvokeRequest> _parser = new pb::MessageParser<OperationInvokeRequest>(() => new OperationInvokeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperationInvokeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.Aas.GRPC.Lib.V3.Services.Operational.DigitalTwinLayerOperationalServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInvokeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInvokeRequest(OperationInvokeRequest other) : this() {
      requestId_ = other.requestId_;
      submodelId_ = other.submodelId_;
      operationIdShort_ = other.operationIdShort_;
      inputVariables_ = other.inputVariables_.Clone();
      inoutVariables_ = other.inoutVariables_.Clone();
      timestamp_ = other.timestamp_;
      isAsync_ = other.isAsync_;
      handleId_ = other.handleId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInvokeRequest Clone() {
      return new OperationInvokeRequest(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "submodelId" field.</summary>
    public const int SubmodelIdFieldNumber = 2;
    private string submodelId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SubmodelId {
      get { return submodelId_; }
      set {
        submodelId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operationIdShort" field.</summary>
    public const int OperationIdShortFieldNumber = 3;
    private string operationIdShort_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OperationIdShort {
      get { return operationIdShort_; }
      set {
        operationIdShort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inputVariables" field.</summary>
    public const int InputVariablesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> _repeated_inputVariables_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> inputVariables_ = new pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> InputVariables {
      get { return inputVariables_; }
    }

    /// <summary>Field number for the "inoutVariables" field.</summary>
    public const int InoutVariablesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> _repeated_inoutVariables_codec
        = pb::FieldCodec.ForMessage(42, global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> inoutVariables_ = new pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.Aas.GRPC.Lib.V3.OperationVariableDTO> InoutVariables {
      get { return inoutVariables_; }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 6;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "isAsync" field.</summary>
    public const int IsAsyncFieldNumber = 7;
    private bool isAsync_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAsync {
      get { return isAsync_; }
      set {
        isAsync_ = value;
      }
    }

    /// <summary>Field number for the "handleId" field.</summary>
    public const int HandleIdFieldNumber = 8;
    private string handleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HandleId {
      get { return handleId_; }
      set {
        handleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperationInvokeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperationInvokeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (SubmodelId != other.SubmodelId) return false;
      if (OperationIdShort != other.OperationIdShort) return false;
      if(!inputVariables_.Equals(other.inputVariables_)) return false;
      if(!inoutVariables_.Equals(other.inoutVariables_)) return false;
      if (Timestamp != other.Timestamp) return false;
      if (IsAsync != other.IsAsync) return false;
      if (HandleId != other.HandleId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (SubmodelId.Length != 0) hash ^= SubmodelId.GetHashCode();
      if (OperationIdShort.Length != 0) hash ^= OperationIdShort.GetHashCode();
      hash ^= inputVariables_.GetHashCode();
      hash ^= inoutVariables_.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (IsAsync != false) hash ^= IsAsync.GetHashCode();
      if (HandleId.Length != 0) hash ^= HandleId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (SubmodelId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubmodelId);
      }
      if (OperationIdShort.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OperationIdShort);
      }
      inputVariables_.WriteTo(output, _repeated_inputVariables_codec);
      inoutVariables_.WriteTo(output, _repeated_inoutVariables_codec);
      if (Timestamp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Timestamp);
      }
      if (IsAsync != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsAsync);
      }
      if (HandleId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(HandleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (SubmodelId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubmodelId);
      }
      if (OperationIdShort.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OperationIdShort);
      }
      size += inputVariables_.CalculateSize(_repeated_inputVariables_codec);
      size += inoutVariables_.CalculateSize(_repeated_inoutVariables_codec);
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (IsAsync != false) {
        size += 1 + 1;
      }
      if (HandleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HandleId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperationInvokeRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.SubmodelId.Length != 0) {
        SubmodelId = other.SubmodelId;
      }
      if (other.OperationIdShort.Length != 0) {
        OperationIdShort = other.OperationIdShort;
      }
      inputVariables_.Add(other.inputVariables_);
      inoutVariables_.Add(other.inoutVariables_);
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.IsAsync != false) {
        IsAsync = other.IsAsync;
      }
      if (other.HandleId.Length != 0) {
        HandleId = other.HandleId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 18: {
            SubmodelId = input.ReadString();
            break;
          }
          case 26: {
            OperationIdShort = input.ReadString();
            break;
          }
          case 34: {
            inputVariables_.AddEntriesFrom(input, _repeated_inputVariables_codec);
            break;
          }
          case 42: {
            inoutVariables_.AddEntriesFrom(input, _repeated_inoutVariables_codec);
            break;
          }
          case 48: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 56: {
            IsAsync = input.ReadBool();
            break;
          }
          case 66: {
            HandleId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OperationRequest : pb::IMessage<OperationRequest> {
    private static readonly pb::MessageParser<OperationRequest> _parser = new pb::MessageParser<OperationRequest>(() => new OperationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.Aas.GRPC.Lib.V3.Services.Operational.DigitalTwinLayerOperationalServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationRequest(OperationRequest other) : this() {
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationRequest Clone() {
      return new OperationRequest(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperationRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OperationStatus : pb::IMessage<OperationStatus> {
    private static readonly pb::MessageParser<OperationStatus> _parser = new pb::MessageParser<OperationStatus>(() => new OperationStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperationStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.Aas.GRPC.Lib.V3.Services.Operational.DigitalTwinLayerOperationalServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationStatus(OperationStatus other) : this() {
      requestId_ = other.requestId_;
      executionState_ = other.executionState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationStatus Clone() {
      return new OperationStatus(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "executionState" field.</summary>
    public const int ExecutionStateFieldNumber = 2;
    private global::FSR.Aas.GRPC.Lib.V3.Services.ExecutionState executionState_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.Aas.GRPC.Lib.V3.Services.ExecutionState ExecutionState {
      get { return executionState_; }
      set {
        executionState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperationStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperationStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (ExecutionState != other.ExecutionState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (ExecutionState != 0) hash ^= ExecutionState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (ExecutionState != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ExecutionState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (ExecutionState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ExecutionState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperationStatus other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.ExecutionState != 0) {
        ExecutionState = other.ExecutionState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 16: {
            ExecutionState = (global::FSR.Aas.GRPC.Lib.V3.Services.ExecutionState) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
