PREFIX so: <http://schema.org/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX DUL: <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX soho: <http://pst.istc.cnr.it/ontologies/2019/01/soho#>
PREFIX sobots: <https://www.uni-augsburg.de/de/fakultaet/fai/informatik/prof/pi/projekte/forschung/forsocialrobots/sobots#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?human ?name ?embodidment
WHERE {
    ?human rdf:type soho:Human .
    OPTIONAL { 
        ?human soho:hasEmbodiment ?embodidment . 
        ?embodidment rdf:type soho:ProductionObject . 
    }
    OPTIONAL { ?human rdfs:label ?name . }
}