# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Services/Connection/PoseStreamingService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protos/Services/Connection/PoseStreamingService.proto',
  package='FSR.DigitalTwinLayer.GRPC.Lib',
  syntax='proto3',
  serialized_options=_b('\252\0021FSR.DigitalTwinLayer.GRPC.Lib.Services.Connection'),
  serialized_pb=_b('\n5Protos/Services/Connection/PoseStreamingService.proto\x12\x1d\x46SR.DigitalTwinLayer.GRPC.Lib\"C\n\x0cPoseLandmark\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x12\n\nvisibility\x18\x04 \x01(\x02\"\x19\n\x17GetPoseLandmarksRequest\"^\n\x18GetPoseLandmarksResponse\x12\x42\n\rposeLandmarks\x18\x01 \x03(\x0b\x32+.FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark\"H\n\x11WorldPoseLandmark\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x12\n\nvisibility\x18\x04 \x01(\x02\"\x1e\n\x1cGetWorldPoseLandmarksRequest\"m\n\x1dGetWorldPoseLandmarksResponse\x12L\n\x12worldPoseLandmarks\x18\x01 \x03(\x0b\x32\x30.FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark2\xaa\x02\n\rPoseStreaming\x12\x83\x01\n\x10GetPoseLandmarks\x12\x36.FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksRequest\x1a\x37.FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksResponse\x12\x92\x01\n\x15GetWorldPoseLandmarks\x12;.FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksRequest\x1a<.FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksResponseB4\xaa\x02\x31\x46SR.DigitalTwinLayer.GRPC.Lib.Services.Connectionb\x06proto3')
)




_POSELANDMARK = _descriptor.Descriptor(
  name='PoseLandmark',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark.visibility', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=155,
)


_GETPOSELANDMARKSREQUEST = _descriptor.Descriptor(
  name='GetPoseLandmarksRequest',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=182,
)


_GETPOSELANDMARKSRESPONSE = _descriptor.Descriptor(
  name='GetPoseLandmarksResponse',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poseLandmarks', full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksResponse.poseLandmarks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=278,
)


_WORLDPOSELANDMARK = _descriptor.Descriptor(
  name='WorldPoseLandmark',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark.visibility', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=352,
)


_GETWORLDPOSELANDMARKSREQUEST = _descriptor.Descriptor(
  name='GetWorldPoseLandmarksRequest',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=384,
)


_GETWORLDPOSELANDMARKSRESPONSE = _descriptor.Descriptor(
  name='GetWorldPoseLandmarksResponse',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldPoseLandmarks', full_name='FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksResponse.worldPoseLandmarks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=495,
)

_GETPOSELANDMARKSRESPONSE.fields_by_name['poseLandmarks'].message_type = _POSELANDMARK
_GETWORLDPOSELANDMARKSRESPONSE.fields_by_name['worldPoseLandmarks'].message_type = _WORLDPOSELANDMARK
DESCRIPTOR.message_types_by_name['PoseLandmark'] = _POSELANDMARK
DESCRIPTOR.message_types_by_name['GetPoseLandmarksRequest'] = _GETPOSELANDMARKSREQUEST
DESCRIPTOR.message_types_by_name['GetPoseLandmarksResponse'] = _GETPOSELANDMARKSRESPONSE
DESCRIPTOR.message_types_by_name['WorldPoseLandmark'] = _WORLDPOSELANDMARK
DESCRIPTOR.message_types_by_name['GetWorldPoseLandmarksRequest'] = _GETWORLDPOSELANDMARKSREQUEST
DESCRIPTOR.message_types_by_name['GetWorldPoseLandmarksResponse'] = _GETWORLDPOSELANDMARKSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoseLandmark = _reflection.GeneratedProtocolMessageType('PoseLandmark', (_message.Message,), {
  'DESCRIPTOR' : _POSELANDMARK,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.PoseLandmark)
  })
_sym_db.RegisterMessage(PoseLandmark)

GetPoseLandmarksRequest = _reflection.GeneratedProtocolMessageType('GetPoseLandmarksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSELANDMARKSREQUEST,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksRequest)
  })
_sym_db.RegisterMessage(GetPoseLandmarksRequest)

GetPoseLandmarksResponse = _reflection.GeneratedProtocolMessageType('GetPoseLandmarksResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSELANDMARKSRESPONSE,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.GetPoseLandmarksResponse)
  })
_sym_db.RegisterMessage(GetPoseLandmarksResponse)

WorldPoseLandmark = _reflection.GeneratedProtocolMessageType('WorldPoseLandmark', (_message.Message,), {
  'DESCRIPTOR' : _WORLDPOSELANDMARK,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.WorldPoseLandmark)
  })
_sym_db.RegisterMessage(WorldPoseLandmark)

GetWorldPoseLandmarksRequest = _reflection.GeneratedProtocolMessageType('GetWorldPoseLandmarksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWORLDPOSELANDMARKSREQUEST,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksRequest)
  })
_sym_db.RegisterMessage(GetWorldPoseLandmarksRequest)

GetWorldPoseLandmarksResponse = _reflection.GeneratedProtocolMessageType('GetWorldPoseLandmarksResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETWORLDPOSELANDMARKSRESPONSE,
  '__module__' : 'Protos.Services.Connection.PoseStreamingService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.GetWorldPoseLandmarksResponse)
  })
_sym_db.RegisterMessage(GetWorldPoseLandmarksResponse)


DESCRIPTOR._options = None

_POSESTREAMING = _descriptor.ServiceDescriptor(
  name='PoseStreaming',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=498,
  serialized_end=796,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPoseLandmarks',
    full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming.GetPoseLandmarks',
    index=0,
    containing_service=None,
    input_type=_GETPOSELANDMARKSREQUEST,
    output_type=_GETPOSELANDMARKSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetWorldPoseLandmarks',
    full_name='FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming.GetWorldPoseLandmarks',
    index=1,
    containing_service=None,
    input_type=_GETWORLDPOSELANDMARKSREQUEST,
    output_type=_GETWORLDPOSELANDMARKSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSESTREAMING)

DESCRIPTOR.services_by_name['PoseStreaming'] = _POSESTREAMING

# @@protoc_insertion_point(module_scope)
