// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/HRCProcessSimulationService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService {

  /// <summary>Holder for reflection information generated from Protos/Services/HRCProcessSimulationService.proto</summary>
  public static partial class HRCProcessSimulationServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/HRCProcessSimulationService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HRCProcessSimulationServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFQcm90b3MvU2VydmljZXMvSFJDUHJvY2Vzc1NpbXVsYXRpb25TZXJ2aWNl",
            "LnByb3RvEhhGU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMaEVByb3Rvcy9CYXNl",
            "LnByb3RvGhpQcm90b3MvRFRPL0hSQ01vZGVscy5wcm90byIpChdEZWNvbXBv",
            "c2VIUkNUYXNrUmVxdWVzdBIOCgZ0YXNrSWQYASABKAkiVQobR2V0U2ltdWxh",
            "dGlvbkNvbnRleHRSZXF1ZXN0EhAKCGNsaWVudElkGAEgASgJEhMKC2Rpc3Bs",
            "YXlOYW1lGAIgASgJEg8KB2hvcml6b24YAyABKAIilwEKHkhSQ1Byb2Nlc3NT",
            "aW11bGF0aW9uQ29udGV4dERUTxIKCgJpZBgBIAEoCRIQCghjbGllbnRJZBgC",
            "IAEoCRITCgtkaXNwbGF5TmFtZRgDIAEoCRI0CgVtb2RlbBgEIAEoCzIlLkZT",
            "Ui5EaWdpdGFsVHdpbi5BcHAuR1JQQy5IUkNNb2RlbERUTxIMCgRkYXRhGAUg",
            "ASgMIu4BChpIUkNQcm9jZXNzU2ltdWxhdGlvbkxvZ0RUTxJJCgdjb250ZXh0",
            "GAEgASgLMjguRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLkhSQ1Byb2Nlc3NT",
            "aW11bGF0aW9uQ29udGV4dERUTxIRCglzdWNjZWVkZWQYAiABKAgSFwoPc2lt",
            "dWxhdGlvblN0YXJ0GAMgASgCEhUKDXNpbXVsYXRpb25FbmQYBCABKAISNAoF",
            "bW9kZWwYBSABKAsyJS5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuSFJDTW9k",
            "ZWxEVE8SDAoEZGF0YRgGIAEoDDLzBgobSFJDUHJvY2Vzc1NpbXVsYXRpb25T",
            "ZXJ2aWNlEocBChRHZXRTaW11bGF0aW9uQ29udGV4dBI1LkZTUi5EaWdpdGFs",
            "VHdpbi5BcHAuR1JQQy5HZXRTaW11bGF0aW9uQ29udGV4dFJlcXVlc3QaOC5G",
            "U1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuSFJDUHJvY2Vzc1NpbXVsYXRpb25D",
            "b250ZXh0RFRPEmoKEVNlbmRTaW11bGF0aW9uTG9nEjQuRlNSLkRpZ2l0YWxU",
            "d2luLkFwcC5HUlBDLkhSQ1Byb2Nlc3NTaW11bGF0aW9uTG9nRFRPGh8uRlNS",
            "LkRpZ2l0YWxUd2luLkFwcC5HUlBDLkVtcHR5El8KF0dldFByb2Nlc3NEZWNv",
            "bXBvc2l0aW9uEiEuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLkdvYWxEVE8a",
            "IS5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuR29hbERUTxJyChdHZXRGdW5j",
            "dGlvblByb3BlcnR5RGF0YRIkLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5I",
            "UkNUYXNrRFRPGjEuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLkZ1bmN0aW9u",
            "UHJvcGVydHlEYXRhRFRPEm4KFUdldEZ1bmN0aW9uT2JqZWN0RGF0YRIkLkZT",
            "Ui5EaWdpdGFsVHdpbi5BcHAuR1JQQy5IUkNUYXNrRFRPGi8uRlNSLkRpZ2l0",
            "YWxUd2luLkFwcC5HUlBDLkZ1bmN0aW9uT2JqZWN0RGF0YURUTxJtChZHZXRJ",
            "bnRlcmFjdGlvbk1vZGFsaXR5EiEuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBD",
            "LlRhc2tEVE8aMC5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuSW50ZXJhY3Rp",
            "b25Nb2RhbGl0eURUTxJVCgxHZXRBbGxBZ2VudHMSHy5GU1IuRGlnaXRhbFR3",
            "aW4uQXBwLkdSUEMuRW1wdHkaIi5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMu",
            "QWdlbnREVE8wARJTCgtHZXRBbGxHb2FscxIfLkZTUi5EaWdpdGFsVHdpbi5B",
            "cHAuR1JQQy5FbXB0eRohLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5Hb2Fs",
            "RFRPMAFCTKoCSUZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5Qcm9jZXNzLkhS",
            "Qy5TZXJ2aWNlcy5IUkNQcm9jZXNzU2ltdWxhdGlvblNlcnZpY2ViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.DigitalTwin.App.GRPC.BaseReflection.Descriptor, global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.DecomposeHRCTaskRequest), global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.DecomposeHRCTaskRequest.Parser, new[]{ "TaskId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.GetSimulationContextRequest), global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.GetSimulationContextRequest.Parser, new[]{ "ClientId", "DisplayName", "Horizon" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO), global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO.Parser, new[]{ "Id", "ClientId", "DisplayName", "Model", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationLogDTO), global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationLogDTO.Parser, new[]{ "Context", "Succeeded", "SimulationStart", "SimulationEnd", "Model", "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DecomposeHRCTaskRequest : pb::IMessage<DecomposeHRCTaskRequest> {
    private static readonly pb::MessageParser<DecomposeHRCTaskRequest> _parser = new pb::MessageParser<DecomposeHRCTaskRequest>(() => new DecomposeHRCTaskRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DecomposeHRCTaskRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DecomposeHRCTaskRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DecomposeHRCTaskRequest(DecomposeHRCTaskRequest other) : this() {
      taskId_ = other.taskId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DecomposeHRCTaskRequest Clone() {
      return new DecomposeHRCTaskRequest(this);
    }

    /// <summary>Field number for the "taskId" field.</summary>
    public const int TaskIdFieldNumber = 1;
    private string taskId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskId {
      get { return taskId_; }
      set {
        taskId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DecomposeHRCTaskRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DecomposeHRCTaskRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskId != other.TaskId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskId.Length != 0) hash ^= TaskId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TaskId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DecomposeHRCTaskRequest other) {
      if (other == null) {
        return;
      }
      if (other.TaskId.Length != 0) {
        TaskId = other.TaskId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaskId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetSimulationContextRequest : pb::IMessage<GetSimulationContextRequest> {
    private static readonly pb::MessageParser<GetSimulationContextRequest> _parser = new pb::MessageParser<GetSimulationContextRequest>(() => new GetSimulationContextRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetSimulationContextRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSimulationContextRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSimulationContextRequest(GetSimulationContextRequest other) : this() {
      clientId_ = other.clientId_;
      displayName_ = other.displayName_;
      horizon_ = other.horizon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSimulationContextRequest Clone() {
      return new GetSimulationContextRequest(this);
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private string clientId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "displayName" field.</summary>
    public const int DisplayNameFieldNumber = 2;
    private string displayName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "horizon" field.</summary>
    public const int HorizonFieldNumber = 3;
    private float horizon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Horizon {
      get { return horizon_; }
      set {
        horizon_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetSimulationContextRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetSimulationContextRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (DisplayName != other.DisplayName) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Horizon, other.Horizon)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (Horizon != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Horizon);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientId);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DisplayName);
      }
      if (Horizon != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Horizon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (Horizon != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetSimulationContextRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.Horizon != 0F) {
        Horizon = other.Horizon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientId = input.ReadString();
            break;
          }
          case 18: {
            DisplayName = input.ReadString();
            break;
          }
          case 29: {
            Horizon = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HRCProcessSimulationContextDTO : pb::IMessage<HRCProcessSimulationContextDTO> {
    private static readonly pb::MessageParser<HRCProcessSimulationContextDTO> _parser = new pb::MessageParser<HRCProcessSimulationContextDTO>(() => new HRCProcessSimulationContextDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HRCProcessSimulationContextDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationContextDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationContextDTO(HRCProcessSimulationContextDTO other) : this() {
      id_ = other.id_;
      clientId_ = other.clientId_;
      displayName_ = other.displayName_;
      model_ = other.model_ != null ? other.model_.Clone() : null;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationContextDTO Clone() {
      return new HRCProcessSimulationContextDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 2;
    private string clientId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "displayName" field.</summary>
    public const int DisplayNameFieldNumber = 3;
    private string displayName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 4;
    private global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO model_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HRCProcessSimulationContextDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HRCProcessSimulationContextDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ClientId != other.ClientId) return false;
      if (DisplayName != other.DisplayName) return false;
      if (!object.Equals(Model, other.Model)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (model_ != null) hash ^= Model.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientId);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      if (model_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Model);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (model_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Model);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HRCProcessSimulationContextDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.model_ != null) {
        if (model_ == null) {
          Model = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO();
        }
        Model.MergeFrom(other.Model);
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ClientId = input.ReadString();
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            if (model_ == null) {
              Model = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO();
            }
            input.ReadMessage(Model);
            break;
          }
          case 42: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HRCProcessSimulationLogDTO : pb::IMessage<HRCProcessSimulationLogDTO> {
    private static readonly pb::MessageParser<HRCProcessSimulationLogDTO> _parser = new pb::MessageParser<HRCProcessSimulationLogDTO>(() => new HRCProcessSimulationLogDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HRCProcessSimulationLogDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationLogDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationLogDTO(HRCProcessSimulationLogDTO other) : this() {
      context_ = other.context_ != null ? other.context_.Clone() : null;
      succeeded_ = other.succeeded_;
      simulationStart_ = other.simulationStart_;
      simulationEnd_ = other.simulationEnd_;
      model_ = other.model_ != null ? other.model_.Clone() : null;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HRCProcessSimulationLogDTO Clone() {
      return new HRCProcessSimulationLogDTO(this);
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 1;
    private global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO context_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    /// <summary>Field number for the "succeeded" field.</summary>
    public const int SucceededFieldNumber = 2;
    private bool succeeded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Succeeded {
      get { return succeeded_; }
      set {
        succeeded_ = value;
      }
    }

    /// <summary>Field number for the "simulationStart" field.</summary>
    public const int SimulationStartFieldNumber = 3;
    private float simulationStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float SimulationStart {
      get { return simulationStart_; }
      set {
        simulationStart_ = value;
      }
    }

    /// <summary>Field number for the "simulationEnd" field.</summary>
    public const int SimulationEndFieldNumber = 4;
    private float simulationEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float SimulationEnd {
      get { return simulationEnd_; }
      set {
        simulationEnd_ = value;
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 5;
    private global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO model_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 6;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HRCProcessSimulationLogDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HRCProcessSimulationLogDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Context, other.Context)) return false;
      if (Succeeded != other.Succeeded) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SimulationStart, other.SimulationStart)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SimulationEnd, other.SimulationEnd)) return false;
      if (!object.Equals(Model, other.Model)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (context_ != null) hash ^= Context.GetHashCode();
      if (Succeeded != false) hash ^= Succeeded.GetHashCode();
      if (SimulationStart != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SimulationStart);
      if (SimulationEnd != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SimulationEnd);
      if (model_ != null) hash ^= Model.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (context_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Context);
      }
      if (Succeeded != false) {
        output.WriteRawTag(16);
        output.WriteBool(Succeeded);
      }
      if (SimulationStart != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(SimulationStart);
      }
      if (SimulationEnd != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(SimulationEnd);
      }
      if (model_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Model);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (context_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Context);
      }
      if (Succeeded != false) {
        size += 1 + 1;
      }
      if (SimulationStart != 0F) {
        size += 1 + 4;
      }
      if (SimulationEnd != 0F) {
        size += 1 + 4;
      }
      if (model_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Model);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HRCProcessSimulationLogDTO other) {
      if (other == null) {
        return;
      }
      if (other.context_ != null) {
        if (context_ == null) {
          Context = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO();
        }
        Context.MergeFrom(other.Context);
      }
      if (other.Succeeded != false) {
        Succeeded = other.Succeeded;
      }
      if (other.SimulationStart != 0F) {
        SimulationStart = other.SimulationStart;
      }
      if (other.SimulationEnd != 0F) {
        SimulationEnd = other.SimulationEnd;
      }
      if (other.model_ != null) {
        if (model_ == null) {
          Model = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO();
        }
        Model.MergeFrom(other.Model);
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (context_ == null) {
              Context = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationContextDTO();
            }
            input.ReadMessage(Context);
            break;
          }
          case 16: {
            Succeeded = input.ReadBool();
            break;
          }
          case 29: {
            SimulationStart = input.ReadFloat();
            break;
          }
          case 37: {
            SimulationEnd = input.ReadFloat();
            break;
          }
          case 42: {
            if (model_ == null) {
              Model = new global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO();
            }
            input.ReadMessage(Model);
            break;
          }
          case 50: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
