// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/SubmodelRepositoryService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository {

  /// <summary>Holder for reflection information generated from Protos/Services/SubmodelRepositoryService.proto</summary>
  public static partial class SubmodelRepositoryServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/SubmodelRepositoryService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SubmodelRepositoryServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9Qcm90b3MvU2VydmljZXMvU3VibW9kZWxSZXBvc2l0b3J5U2VydmljZS5w",
            "cm90bxIYRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDGh1Qcm90b3MvRFRPL0Fh",
            "c01vZGVscy5WMy5wcm90bxogUHJvdG9zL0RUTy9BYXNBcGlNb2RlbHMuVjMu",
            "cHJvdG8iXQoZR2V0QWxsU3VibW9kZWxzUnBjUmVxdWVzdBJACg5vdXRwdXRN",
            "b2RpZmllchgBIAEoCzIoLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5PdXRw",
            "dXRNb2RpZmllciLwAQoaR2V0QWxsU3VibW9kZWxzUnBjUmVzcG9uc2USEgoK",
            "c3RhdHVzQ29kZRgBIAEoBRJLCg5wYWdpbmdNZXRhRGF0YRgCIAEoCzIzLkZT",
            "Ui5EaWdpdGFsVHdpbi5BcHAuR1JQQy5QYWdlZFJlc3VsdFBhZ2luZ01ldGFk",
            "YXRhEjYKB3BheWxvYWQYAyADKAsyJS5GU1IuRGlnaXRhbFR3aW4uQXBwLkdS",
            "UEMuU3VibW9kZWxEVE8SOQoJcmVmZXJlbmNlGAQgAygLMiYuRlNSLkRpZ2l0",
            "YWxUd2luLkFwcC5HUlBDLlJlZmVyZW5jZURUTyJpChlHZXRTdWJtb2RlbEJ5",
            "SWRScGNSZXF1ZXN0EgoKAmlkGAEgASgJEkAKDm91dHB1dE1vZGlmaWVyGAIg",
            "ASgLMiguRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLk91dHB1dE1vZGlmaWVy",
            "IqMBChpHZXRTdWJtb2RlbEJ5SWRScGNSZXNwb25zZRISCgpzdGF0dXNDb2Rl",
            "GAEgASgFEjYKB3BheWxvYWQYAiABKAsyJS5GU1IuRGlnaXRhbFR3aW4uQXBw",
            "LkdSUEMuU3VibW9kZWxEVE8SOQoJcmVmZXJlbmNlGAMgASgLMiYuRlNSLkRp",
            "Z2l0YWxUd2luLkFwcC5HUlBDLlJlZmVyZW5jZURUTyKlAQolR2V0QWxsU3Vi",
            "bW9kZWxzQnlTZW1hbnRpY0lkUnBjUmVxdWVzdBI6CgpzZW1hbnRpY0lkGAEg",
            "ASgLMiYuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLlJlZmVyZW5jZURUTxJA",
            "Cg5vdXRwdXRNb2RpZmllchgCIAEoCzIoLkZTUi5EaWdpdGFsVHdpbi5BcHAu",
            "R1JQQy5PdXRwdXRNb2RpZmllciL8AQomR2V0QWxsU3VibW9kZWxzQnlTZW1h",
            "bnRpY0lkUnBjUmVzcG9uc2USEgoKc3RhdHVzQ29kZRgBIAEoBRJLCg5wYWdp",
            "bmdNZXRhRGF0YRgCIAEoCzIzLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5Q",
            "YWdlZFJlc3VsdFBhZ2luZ01ldGFkYXRhEjYKB3BheWxvYWQYAyADKAsyJS5G",
            "U1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuU3VibW9kZWxEVE8SOQoJcmVmZXJl",
            "bmNlGAQgAygLMiYuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLlJlZmVyZW5j",
            "ZURUTyJ3CiJHZXRBbGxTdWJtb2RlbHNCeUlkU2hvcnRScGNSZXF1ZXN0Eg8K",
            "B2lkU2hvcnQYASABKAkSQAoOb3V0cHV0TW9kaWZpZXIYAiABKAsyKC5GU1Iu",
            "RGlnaXRhbFR3aW4uQXBwLkdSUEMuT3V0cHV0TW9kaWZpZXIi+QEKI0dldEFs",
            "bFN1Ym1vZGVsc0J5SWRTaG9ydFJwY1Jlc3BvbnNlEhIKCnN0YXR1c0NvZGUY",
            "ASABKAUSSwoOcGFnaW5nTWV0YURhdGEYAiABKAsyMy5GU1IuRGlnaXRhbFR3",
            "aW4uQXBwLkdSUEMuUGFnZWRSZXN1bHRQYWdpbmdNZXRhZGF0YRI2CgdwYXls",
            "b2FkGAMgAygLMiUuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLlN1Ym1vZGVs",
            "RFRPEjkKCXJlZmVyZW5jZRgEIAMoCzImLkZTUi5EaWdpdGFsVHdpbi5BcHAu",
            "R1JQQy5SZWZlcmVuY2VEVE8iaAoWUG9zdFN1Ym1vZGVsUnBjUmVxdWVzdBI3",
            "CghzdWJtb2RlbBgBIAEoCzIlLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5T",
            "dWJtb2RlbERUTxIVCg1hYXNJZGVudGlmaWVyGAIgASgJImYKF1Bvc3RTdWJt",
            "b2RlbFJwY1Jlc3BvbnNlEhIKCnN0YXR1c0NvZGUYASABKAUSNwoIc3VibW9k",
            "ZWwYAiABKAsyJS5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuU3VibW9kZWxE",
            "VE8iVAoZUHV0U3VibW9kZWxCeUlkUnBjUmVxdWVzdBI3CghzdWJtb2RlbBgB",
            "IAEoCzIlLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5TdWJtb2RlbERUTyJp",
            "ChpQdXRTdWJtb2RlbEJ5SWRScGNSZXNwb25zZRISCgpzdGF0dXNDb2RlGAEg",
            "ASgFEjcKCHN1Ym1vZGVsGAIgASgLMiUuRlNSLkRpZ2l0YWxUd2luLkFwcC5H",
            "UlBDLlN1Ym1vZGVsRFRPIioKHERlbGV0ZVN1Ym1vZGVsQnlJZFJwY1JlcXVl",
            "c3QSCgoCaWQYASABKAkiMwodRGVsZXRlU3VibW9kZWxCeUlkUnBjUmVzcG9u",
            "c2USEgoKc3RhdHVzQ29kZRgBIAEoBTLPBwoZU3VibW9kZWxSZXBvc2l0b3J5",
            "U2VydmljZRJ8Cg9HZXRBbGxTdWJtb2RlbHMSMy5GU1IuRGlnaXRhbFR3aW4u",
            "QXBwLkdSUEMuR2V0QWxsU3VibW9kZWxzUnBjUmVxdWVzdBo0LkZTUi5EaWdp",
            "dGFsVHdpbi5BcHAuR1JQQy5HZXRBbGxTdWJtb2RlbHNScGNSZXNwb25zZRJ8",
            "Cg9HZXRTdWJtb2RlbEJ5SWQSMy5GU1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMu",
            "R2V0U3VibW9kZWxCeUlkUnBjUmVxdWVzdBo0LkZTUi5EaWdpdGFsVHdpbi5B",
            "cHAuR1JQQy5HZXRTdWJtb2RlbEJ5SWRScGNSZXNwb25zZRKgAQobR2V0QWxs",
            "U3VibW9kZWxzQnlTZW1hbnRpY0lkEj8uRlNSLkRpZ2l0YWxUd2luLkFwcC5H",
            "UlBDLkdldEFsbFN1Ym1vZGVsc0J5U2VtYW50aWNJZFJwY1JlcXVlc3QaQC5G",
            "U1IuRGlnaXRhbFR3aW4uQXBwLkdSUEMuR2V0QWxsU3VibW9kZWxzQnlTZW1h",
            "bnRpY0lkUnBjUmVzcG9uc2USlwEKGEdldEFsbFN1Ym1vZGVsc0J5SWRTaG9y",
            "dBI8LkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5HZXRBbGxTdWJtb2RlbHNC",
            "eUlkU2hvcnRScGNSZXF1ZXN0Gj0uRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBD",
            "LkdldEFsbFN1Ym1vZGVsc0J5SWRTaG9ydFJwY1Jlc3BvbnNlEnMKDFBvc3RT",
            "dWJtb2RlbBIwLkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5Qb3N0U3VibW9k",
            "ZWxScGNSZXF1ZXN0GjEuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLlBvc3RT",
            "dWJtb2RlbFJwY1Jlc3BvbnNlEnwKD1B1dFN1Ym1vZGVsQnlJZBIzLkZTUi5E",
            "aWdpdGFsVHdpbi5BcHAuR1JQQy5QdXRTdWJtb2RlbEJ5SWRScGNSZXF1ZXN0",
            "GjQuRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLlB1dFN1Ym1vZGVsQnlJZFJw",
            "Y1Jlc3BvbnNlEoUBChJEZWxldGVTdWJtb2RlbEJ5SWQSNi5GU1IuRGlnaXRh",
            "bFR3aW4uQXBwLkdSUEMuRGVsZXRlU3VibW9kZWxCeUlkUnBjUmVxdWVzdBo3",
            "LkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5EZWxldGVTdWJtb2RlbEJ5SWRS",
            "cGNSZXNwb25zZUJCqgI/RlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDLkFhcy5M",
            "aWIuVjMuU2VydmljZXMuU3VibW9kZWxSZXBvc2l0b3J5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.AasModelsV3Reflection.Descriptor, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.AasApiModelsV3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsRpcRequest.Parser, new[]{ "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetSubmodelByIdRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetSubmodelByIdRpcRequest.Parser, new[]{ "Id", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetSubmodelByIdRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetSubmodelByIdRpcResponse.Parser, new[]{ "StatusCode", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsBySemanticIdRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsBySemanticIdRpcRequest.Parser, new[]{ "SemanticId", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsBySemanticIdRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsBySemanticIdRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsByIdShortRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsByIdShortRpcRequest.Parser, new[]{ "IdShort", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsByIdShortRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.GetAllSubmodelsByIdShortRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PostSubmodelRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PostSubmodelRpcRequest.Parser, new[]{ "Submodel", "AasIdentifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PostSubmodelRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PostSubmodelRpcResponse.Parser, new[]{ "StatusCode", "Submodel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PutSubmodelByIdRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PutSubmodelByIdRpcRequest.Parser, new[]{ "Submodel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PutSubmodelByIdRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.PutSubmodelByIdRpcResponse.Parser, new[]{ "StatusCode", "Submodel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.DeleteSubmodelByIdRpcRequest), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.DeleteSubmodelByIdRpcRequest.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.DeleteSubmodelByIdRpcResponse), global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.DeleteSubmodelByIdRpcResponse.Parser, new[]{ "StatusCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetAllSubmodelsRpcRequest : pb::IMessage<GetAllSubmodelsRpcRequest> {
    private static readonly pb::MessageParser<GetAllSubmodelsRpcRequest> _parser = new pb::MessageParser<GetAllSubmodelsRpcRequest>(() => new GetAllSubmodelsRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcRequest(GetAllSubmodelsRpcRequest other) : this() {
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcRequest Clone() {
      return new GetAllSubmodelsRpcRequest(this);
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 1;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (outputModifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelsRpcResponse : pb::IMessage<GetAllSubmodelsRpcResponse> {
    private static readonly pb::MessageParser<GetAllSubmodelsRpcResponse> _parser = new pb::MessageParser<GetAllSubmodelsRpcResponse>(() => new GetAllSubmodelsRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcResponse(GetAllSubmodelsRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsRpcResponse Clone() {
      return new GetAllSubmodelsRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> payload_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> reference_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetSubmodelByIdRpcRequest : pb::IMessage<GetSubmodelByIdRpcRequest> {
    private static readonly pb::MessageParser<GetSubmodelByIdRpcRequest> _parser = new pb::MessageParser<GetSubmodelByIdRpcRequest>(() => new GetSubmodelByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetSubmodelByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcRequest(GetSubmodelByIdRpcRequest other) : this() {
      id_ = other.id_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcRequest Clone() {
      return new GetSubmodelByIdRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetSubmodelByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetSubmodelByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetSubmodelByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetSubmodelByIdRpcResponse : pb::IMessage<GetSubmodelByIdRpcResponse> {
    private static readonly pb::MessageParser<GetSubmodelByIdRpcResponse> _parser = new pb::MessageParser<GetSubmodelByIdRpcResponse>(() => new GetSubmodelByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetSubmodelByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcResponse(GetSubmodelByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      reference_ = other.reference_ != null ? other.reference_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetSubmodelByIdRpcResponse Clone() {
      return new GetSubmodelByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 3;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO reference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO Reference {
      get { return reference_; }
      set {
        reference_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetSubmodelByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetSubmodelByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      if (!object.Equals(Reference, other.Reference)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (reference_ != null) hash ^= Reference.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (payload_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Payload);
      }
      if (reference_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Reference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (reference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetSubmodelByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
        }
        Payload.MergeFrom(other.Payload);
      }
      if (other.reference_ != null) {
        if (reference_ == null) {
          Reference = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO();
        }
        Reference.MergeFrom(other.Reference);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (payload_ == null) {
              Payload = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
            }
            input.ReadMessage(Payload);
            break;
          }
          case 26: {
            if (reference_ == null) {
              Reference = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO();
            }
            input.ReadMessage(Reference);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelsBySemanticIdRpcRequest : pb::IMessage<GetAllSubmodelsBySemanticIdRpcRequest> {
    private static readonly pb::MessageParser<GetAllSubmodelsBySemanticIdRpcRequest> _parser = new pb::MessageParser<GetAllSubmodelsBySemanticIdRpcRequest>(() => new GetAllSubmodelsBySemanticIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsBySemanticIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcRequest(GetAllSubmodelsBySemanticIdRpcRequest other) : this() {
      semanticId_ = other.semanticId_ != null ? other.semanticId_.Clone() : null;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcRequest Clone() {
      return new GetAllSubmodelsBySemanticIdRpcRequest(this);
    }

    /// <summary>Field number for the "semanticId" field.</summary>
    public const int SemanticIdFieldNumber = 1;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO semanticId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO SemanticId {
      get { return semanticId_; }
      set {
        semanticId_ = value;
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsBySemanticIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsBySemanticIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SemanticId, other.SemanticId)) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (semanticId_ != null) hash ^= SemanticId.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (semanticId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SemanticId);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (semanticId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SemanticId);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsBySemanticIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.semanticId_ != null) {
        if (semanticId_ == null) {
          SemanticId = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO();
        }
        SemanticId.MergeFrom(other.SemanticId);
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (semanticId_ == null) {
              SemanticId = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO();
            }
            input.ReadMessage(SemanticId);
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelsBySemanticIdRpcResponse : pb::IMessage<GetAllSubmodelsBySemanticIdRpcResponse> {
    private static readonly pb::MessageParser<GetAllSubmodelsBySemanticIdRpcResponse> _parser = new pb::MessageParser<GetAllSubmodelsBySemanticIdRpcResponse>(() => new GetAllSubmodelsBySemanticIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsBySemanticIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcResponse(GetAllSubmodelsBySemanticIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsBySemanticIdRpcResponse Clone() {
      return new GetAllSubmodelsBySemanticIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> payload_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> reference_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsBySemanticIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsBySemanticIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsBySemanticIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelsByIdShortRpcRequest : pb::IMessage<GetAllSubmodelsByIdShortRpcRequest> {
    private static readonly pb::MessageParser<GetAllSubmodelsByIdShortRpcRequest> _parser = new pb::MessageParser<GetAllSubmodelsByIdShortRpcRequest>(() => new GetAllSubmodelsByIdShortRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsByIdShortRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcRequest(GetAllSubmodelsByIdShortRpcRequest other) : this() {
      idShort_ = other.idShort_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcRequest Clone() {
      return new GetAllSubmodelsByIdShortRpcRequest(this);
    }

    /// <summary>Field number for the "idShort" field.</summary>
    public const int IdShortFieldNumber = 1;
    private string idShort_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdShort {
      get { return idShort_; }
      set {
        idShort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsByIdShortRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsByIdShortRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdShort != other.IdShort) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdShort.Length != 0) hash ^= IdShort.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdShort.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdShort);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdShort.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdShort);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsByIdShortRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdShort.Length != 0) {
        IdShort = other.IdShort;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdShort = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelsByIdShortRpcResponse : pb::IMessage<GetAllSubmodelsByIdShortRpcResponse> {
    private static readonly pb::MessageParser<GetAllSubmodelsByIdShortRpcResponse> _parser = new pb::MessageParser<GetAllSubmodelsByIdShortRpcResponse>(() => new GetAllSubmodelsByIdShortRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelsByIdShortRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcResponse(GetAllSubmodelsByIdShortRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelsByIdShortRpcResponse Clone() {
      return new GetAllSubmodelsByIdShortRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> payload_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> reference_ = new pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.ReferenceDTO> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelsByIdShortRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelsByIdShortRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelsByIdShortRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostSubmodelRpcRequest : pb::IMessage<PostSubmodelRpcRequest> {
    private static readonly pb::MessageParser<PostSubmodelRpcRequest> _parser = new pb::MessageParser<PostSubmodelRpcRequest>(() => new PostSubmodelRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSubmodelRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcRequest(PostSubmodelRpcRequest other) : this() {
      submodel_ = other.submodel_ != null ? other.submodel_.Clone() : null;
      aasIdentifier_ = other.aasIdentifier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcRequest Clone() {
      return new PostSubmodelRpcRequest(this);
    }

    /// <summary>Field number for the "submodel" field.</summary>
    public const int SubmodelFieldNumber = 1;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO submodel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO Submodel {
      get { return submodel_; }
      set {
        submodel_ = value;
      }
    }

    /// <summary>Field number for the "aasIdentifier" field.</summary>
    public const int AasIdentifierFieldNumber = 2;
    private string aasIdentifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AasIdentifier {
      get { return aasIdentifier_; }
      set {
        aasIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSubmodelRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSubmodelRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Submodel, other.Submodel)) return false;
      if (AasIdentifier != other.AasIdentifier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (submodel_ != null) hash ^= Submodel.GetHashCode();
      if (AasIdentifier.Length != 0) hash ^= AasIdentifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (submodel_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Submodel);
      }
      if (AasIdentifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AasIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (submodel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submodel);
      }
      if (AasIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AasIdentifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSubmodelRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.submodel_ != null) {
        if (submodel_ == null) {
          Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
        }
        Submodel.MergeFrom(other.Submodel);
      }
      if (other.AasIdentifier.Length != 0) {
        AasIdentifier = other.AasIdentifier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (submodel_ == null) {
              Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
            }
            input.ReadMessage(Submodel);
            break;
          }
          case 18: {
            AasIdentifier = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostSubmodelRpcResponse : pb::IMessage<PostSubmodelRpcResponse> {
    private static readonly pb::MessageParser<PostSubmodelRpcResponse> _parser = new pb::MessageParser<PostSubmodelRpcResponse>(() => new PostSubmodelRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSubmodelRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcResponse(PostSubmodelRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      submodel_ = other.submodel_ != null ? other.submodel_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelRpcResponse Clone() {
      return new PostSubmodelRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "submodel" field.</summary>
    public const int SubmodelFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO submodel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO Submodel {
      get { return submodel_; }
      set {
        submodel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSubmodelRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSubmodelRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Submodel, other.Submodel)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (submodel_ != null) hash ^= Submodel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (submodel_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Submodel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (submodel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submodel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSubmodelRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.submodel_ != null) {
        if (submodel_ == null) {
          Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
        }
        Submodel.MergeFrom(other.Submodel);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (submodel_ == null) {
              Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
            }
            input.ReadMessage(Submodel);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutSubmodelByIdRpcRequest : pb::IMessage<PutSubmodelByIdRpcRequest> {
    private static readonly pb::MessageParser<PutSubmodelByIdRpcRequest> _parser = new pb::MessageParser<PutSubmodelByIdRpcRequest>(() => new PutSubmodelByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutSubmodelByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcRequest(PutSubmodelByIdRpcRequest other) : this() {
      submodel_ = other.submodel_ != null ? other.submodel_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcRequest Clone() {
      return new PutSubmodelByIdRpcRequest(this);
    }

    /// <summary>Field number for the "submodel" field.</summary>
    public const int SubmodelFieldNumber = 1;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO submodel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO Submodel {
      get { return submodel_; }
      set {
        submodel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutSubmodelByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutSubmodelByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Submodel, other.Submodel)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (submodel_ != null) hash ^= Submodel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (submodel_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Submodel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (submodel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submodel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutSubmodelByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.submodel_ != null) {
        if (submodel_ == null) {
          Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
        }
        Submodel.MergeFrom(other.Submodel);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (submodel_ == null) {
              Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
            }
            input.ReadMessage(Submodel);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutSubmodelByIdRpcResponse : pb::IMessage<PutSubmodelByIdRpcResponse> {
    private static readonly pb::MessageParser<PutSubmodelByIdRpcResponse> _parser = new pb::MessageParser<PutSubmodelByIdRpcResponse>(() => new PutSubmodelByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutSubmodelByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcResponse(PutSubmodelByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      submodel_ = other.submodel_ != null ? other.submodel_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutSubmodelByIdRpcResponse Clone() {
      return new PutSubmodelByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "submodel" field.</summary>
    public const int SubmodelFieldNumber = 2;
    private global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO submodel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO Submodel {
      get { return submodel_; }
      set {
        submodel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutSubmodelByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutSubmodelByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Submodel, other.Submodel)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (submodel_ != null) hash ^= Submodel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (submodel_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Submodel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (submodel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submodel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutSubmodelByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.submodel_ != null) {
        if (submodel_ == null) {
          Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
        }
        Submodel.MergeFrom(other.Submodel);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (submodel_ == null) {
              Submodel = new global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.SubmodelDTO();
            }
            input.ReadMessage(Submodel);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteSubmodelByIdRpcRequest : pb::IMessage<DeleteSubmodelByIdRpcRequest> {
    private static readonly pb::MessageParser<DeleteSubmodelByIdRpcRequest> _parser = new pb::MessageParser<DeleteSubmodelByIdRpcRequest>(() => new DeleteSubmodelByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteSubmodelByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcRequest(DeleteSubmodelByIdRpcRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcRequest Clone() {
      return new DeleteSubmodelByIdRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteSubmodelByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteSubmodelByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteSubmodelByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteSubmodelByIdRpcResponse : pb::IMessage<DeleteSubmodelByIdRpcResponse> {
    private static readonly pb::MessageParser<DeleteSubmodelByIdRpcResponse> _parser = new pb::MessageParser<DeleteSubmodelByIdRpcResponse>(() => new DeleteSubmodelByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteSubmodelByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Aas.Lib.V3.Services.SubmodelRepository.SubmodelRepositoryServiceReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcResponse(DeleteSubmodelByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelByIdRpcResponse Clone() {
      return new DeleteSubmodelByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteSubmodelByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteSubmodelByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteSubmodelByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
