# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Protos.Services.Connection import PoseStreamingService_pb2 as Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2


class PoseStreamingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPoseLandmarks = channel.unary_unary(
        '/FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming/GetPoseLandmarks',
        request_serializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetPoseLandmarksRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetPoseLandmarksResponse.FromString,
        )
    self.GetWorldPoseLandmarks = channel.unary_unary(
        '/FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming/GetWorldPoseLandmarks',
        request_serializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetWorldPoseLandmarksRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetWorldPoseLandmarksResponse.FromString,
        )


class PoseStreamingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPoseLandmarks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWorldPoseLandmarks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoseStreamingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPoseLandmarks': grpc.unary_unary_rpc_method_handler(
          servicer.GetPoseLandmarks,
          request_deserializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetPoseLandmarksRequest.FromString,
          response_serializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetPoseLandmarksResponse.SerializeToString,
      ),
      'GetWorldPoseLandmarks': grpc.unary_unary_rpc_method_handler(
          servicer.GetWorldPoseLandmarks,
          request_deserializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetWorldPoseLandmarksRequest.FromString,
          response_serializer=Protos_dot_Services_dot_Connection_dot_PoseStreamingService__pb2.GetWorldPoseLandmarksResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FSR.DigitalTwinLayer.GRPC.Lib.PoseStreaming', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
