syntax = "proto3";

option csharp_namespace = "FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService";

import "Protos/Base.proto";
import "Protos/DTO/HRCModels.proto";

package FSR.DigitalTwin.App.GRPC;

message DecomposeHRCTaskRequest {
    string taskId = 1;
}

message GetSimulationContextRequest {
    string clientId = 1;
    string displayName = 2;
    float horizon = 3;
}

message HRCProcessSimulationContextDTO {
    string id = 1;
    string clientId = 2;
    string displayName = 3;
    HRCModelDTO model = 4;
    bytes data = 5;
}

message HRCProcessSimulationLogDTO {
    HRCProcessSimulationContextDTO context = 1;
    bool succeeded = 2;
    float simulationStart = 3;
    float simulationEnd = 4;
    HRCModelDTO model = 5;
    bytes data = 6;
}

service HRCProcessSimulationService {
    rpc GetSimulationContext (GetSimulationContextRequest) returns (HRCProcessSimulationContextDTO);
    rpc SendSimulationLog (HRCProcessSimulationLogDTO) returns (Empty);
    rpc GetProcessDecomposition (GoalDTO) returns (GoalDTO);
    // rpc GetProcessDependencies (GoalDTO) returns (TaskDTO);
    rpc GetFunctionPropertyData (HRCTaskDTO) returns (FunctionPropertyDataDTO);
    rpc GetFunctionObjectData (HRCTaskDTO) returns (FunctionObjectDataDTO);
    rpc GetInteractionModality (TaskDTO) returns (InteractionModalityDTO);
    rpc GetAllAgents (Empty) returns (stream AgentDTO);
    rpc GetAllGoals (Empty) returns (stream GoalDTO);
}